### ISSUE TITLE
About the path and configuration of tun2socks.yml

### ISSUE THREAD

**Issue by Cyberbolt** [SaeedDev94/Xray#13]
https://github.com/SaeedDev94/Xray/blob/57a8d92f311d15cfa0c45cb0606dcca649373d5d/app/src/main/java/com/xtls/xray/Settings.kt#L22

May I ask in which directory this file is placed?

What is the content of the configuration file? I looked at [Configuration File](https://github.com/heiher/hev-socks5-tunnel?tab=readme-ov-file#config). There should be no need to configure Tun in Android development? How did you configure it?

**Comment by SaeedDev94** [comment]
> May I ask in which directory this file is placed?

`/data/data/com.xtls.xray/files`
You need root access

**Comment by Cyberbolt** [comment]
@SaeedDev94 In other words, it is only useful if you have root permissions to read tun2socks.yml. Otherwise, use MainApplication.kt to configure it directly? Can I just change the parameters here directly?
```
object Settings {
     var socksAddress: String = "127.0.0.1"
     var socksPort: String = "10808"
     var socksUdp: Boolean = true
     var primaryDns: String = "1.1.1.1"
     var secondaryDns: String = "1.0.0.1"
     var excludedApps: String = ""
     var useXray: Boolean = false
     var tunName: String = "tun0"
     var tunMtu: Int = 1500
     var tunGateway: String = "10.14.1.1"
     var tunAddress: String = "10.14.1.2"
     var tunPrefix: Int = 24

     // fun xrayConfig(context: Context): File = File(context.filesDir, "config.json")
     fun tun2socksConfig(context: Context): File = File(context.filesDir, "tun2socks.yml")
     // fun sharedPref(context: Context): SharedPreferences = context.getSharedPreferences("settings", Context.MODE_PRIVATE)
}
```

**Comment by SaeedDev94** [comment]
> Can I just change the parameters here directly?

Yes you can
