### ISSUE TITLE
libXray vs AndroidLibXrayLite

### ISSUE THREAD

**Issue by itsDantes** [SaeedDev94/Xray#18]
what's different between [libXray ](https://github.com/XTLS/libXray) - [AndroidLibXrayLite ](https://github.com/2dust/AndroidLibXrayLite) and this [branches](https://github.com/SaeedDev94/Xray/tree/57a8d92f311d15cfa0c45cb0606dcca649373d5d/app/src/main/jniLibs/arm64-v8a) ? you used 3 different engine during time. i want to know why . does the current libXray engine has better performance?

**Comment by SaeedDev94** [comment]
I started this repo with the idea of running xray-core as command, but it has some issues like dns (outbound domain address couldn't resolve), so I decided to use native go implementation for mobile  
I choose libXray by XTLS because it's easier to use and implement rather than AndroidLibXrayLite
