### ISSUE TITLE
some x-ray configs not working

### ISSUE THREAD

**Issue by JackSonJson** [SaeedDev94/Xray#2]
i found that if config of xray includes (ws) or (grpc) or even (tcp) network,  it not works. 

for example, if you put this config in app,  it not works. 

`
{
  "dns": {
    "hosts": {
      "domain:googleapis.cn": "googleapis.com"
    },
    "servers": [
      "1.1.1.1"
    ]
  },
  "inbounds": [
    {
      "listen": "127.0.0.1",
      "port": 10808,
      "protocol": "socks",
      "settings": {
        "auth": "noauth",
        "udp": true,
        "userLevel": 8
      },
      "sniffing": {
        "destOverride": [
          "http",
          "tls"
        ],
        "enabled": true
      },
      "tag": "socks"
    },
    {
      "listen": "127.0.0.1",
      "port": 10809,
      "protocol": "http",
      "settings": {
        "userLevel": 8
      },
      "tag": "http"
    }
  ],
  "log": {
    "loglevel": "warning"
  },
  "outbounds": [
    {
      "mux": {
        "concurrency": 8,
        "enabled": false
      },
      "protocol": "vless",
      "settings": {
        "vnext": [
          {
            "address": "turkey.legendaryam.xyz",
            "port": 2053,
            "users": [
              {
                "encryption": "none",
                "flow": "",
                "id": "aa7e9f71-c222-47f3-86e4-9ac30435ffed",
                "level": 8,
                "security": "auto"
              }
            ]
          }
        ]
      },
      "streamSettings": {
        "grpcSettings": {
          "multiMode": false,
          "serviceName": "xyz"
        },
        "network": "grpc",
        "realitySettings": {
          "allowInsecure": false,
          "fingerprint": "chrome",
          "publicKey": "WqqDJ7TsdoGf7RAzbtKd485RmUqSw-hebRWMFvKqlQ0",
          "serverName": "creativecommons.org",
          "shortId": "",
          "show": false,
          "spiderX": ""
        },
        "security": "reality"
      },
      "tag": "proxy"
    },
    {
      "protocol": "freedom",
      "settings": {},
      "tag": "direct"
    },
    {
      "protocol": "blackhole",
      "settings": {
        "response": {
          "type": "http"
        }
      },
      "tag": "block"
    }
  ],
  "routing": {
    "domainStrategy": "IPIfNonMatch",
    "rules": [
      {
        "ip": [
          "1.1.1.1"
        ],
        "outboundTag": "proxy",
        "port": "53",
        "type": "field"
      }
    ]
  }
}
`

also some times in some configs, app sends fake speed like below; 

![Picsart_23-09-10_22-50-15-344](https://github.com/Saeed-Pooyanfar/Xray/assets/94376760/5781500c-dec6-4087-95c7-95b279ae41d5)

the tested configs; 
`
{
  "dns": {
    "hosts": {
      "domain:googleapis.cn": "googleapis.com"
    },
    "servers": [
      "1.1.1.1"
    ]
  },
  "inbounds": [
    {
      "listen": "127.0.0.1",
      "port": 10808,
      "protocol": "socks",
      "settings": {
        "auth": "noauth",
        "udp": true,
        "userLevel": 8
      },
      "sniffing": {
        "destOverride": [
          "http",
          "tls"
        ],
        "enabled": true
      },
      "tag": "socks"
    },
    {
      "listen": "127.0.0.1",
      "port": 10809,
      "protocol": "http",
      "settings": {
        "userLevel": 8
      },
      "tag": "http"
    }
  ],
  "log": {
    "loglevel": "warning"
  },
  "outbounds": [
    {
      "mux": {
        "concurrency": 8,
        "enabled": false
      },
      "protocol": "vless",
      "settings": {
        "vnext": [
          {
            "address": "6544.outline-vpn.cloud",
            "port": 2096,
            "users": [
              {
                "encryption": "none",
                "flow": "",
                "id": "e3c633c7-37de-4a73-9064-240b645777bc",
                "level": 8,
                "security": "auto"
              }
            ]
          }
        ]
      },
      "streamSettings": {
        "network": "ws",
        "security": "tls",
        "tlsSettings": {
          "allowInsecure": false,
          "fingerprint": "",
          "publicKey": "",
          "serverName": "sgp.vps.wengmail.link",
          "shortId": "",
          "show": false,
          "spiderX": ""
        },
        "wsSettings": {
          "headers": {
            "Host": "sgp.vps.wengmail.link"
          },
          "path": "/?ed=2048"
        }
      },
      "tag": "proxy"
    },
    {
      "protocol": "freedom",
      "settings": {},
      "tag": "direct"
    },
    {
      "protocol": "blackhole",
      "settings": {
        "response": {
          "type": "http"
        }
      },
      "tag": "block"
    }
  ],
  "routing": {
    "domainStrategy": "IPIfNonMatch",
    "rules": [
      {
        "ip": [
          "1.1.1.1"
        ],
        "outboundTag": "proxy",
        "port": "53",
        "type": "field"
      }
    ]
  }
}
`

is there any problem in the x-ray configs or apps?

**Comment by Saeed-Pooyanfar** [comment]
- This app is using xray cli version and simply pass the json config to xray so It should be fine
- For now this app only supports arm32 and arm64
- Proxy address and port in your json config MUST be same with the app settings

**Comment by Saeed-Pooyanfar** [comment]
Thanks for your interest to my app :)  
I develop it with only one main reason: Possibility to release update fast when new version is available for `XTLS/Xray-core`  
It isn't feature rich at all and for now it doesn't have ping feature to test your active connection, Imagine your are using the CLI version with less complexity :))  
However maybe I'll add it in upcoming versions

**Comment by Anselaaa** [comment]
> 谢谢。您能否提供更多有关获取 ping 或一些有用的配置统计信息的示例？我很高兴看到如何使用您的源代码来完成它。因为你的源代码非常干净且易于理解。我测试了很多库，其中大多数都让我困惑。



> thanks. can you please make more example about getting ping or some useful stats of configs? I'm glad to see how it can done with your source code. because your source code is very clean and understandable. i tested many library and most of them confused me.

Excuse me, did you succeed in the end? How should I configure it? My profile, other apps can connect normally.

**Comment by Anselaaa** [comment]
> > thanks. can you please make more example about getting ping or some useful stats of configs? I'm glad to see how it can done with your source code. because your source code is very clean and understandable. i tested many library and most of them confused me.
> 
> Excuse me, did you succeed in the end? How should I configure it? My profile, other apps can connect normally.
