### ISSUE TITLE
Please change release filename pattern to contain ISA info

### ISSUE THREAD

**Issue by bhoppi** [SaeedDev94/Xray#20]
As title. Now there are just numbers, so I can't figure out which one is x86_64 or armv8 to download.

**Comment by SaeedDev94** [comment]
Because of F-Droid release probably I can't do it, but here is version code guide:  
- arm 32 => versionCode + 1
- arm 64 => versionCode + 2
- x86 => versionCode + 3
- amd64 => versionCode + 4

So for v6.3.0:  
- arm 32 => 251
- arm 64 => 252
- x86 => 253
- amd64 => 254

**Comment by bhoppi** [comment]
Thanks for your reply. Maybe you can put this comment in the readme.
