### ISSUE TITLE
F-Droid can't build

### ISSUE THREAD

**Issue by licaon-kter** [SaeedDev94/Xray#24]
but only this arch: https://monitor.f-droid.org/builds/log/io.github.saeeddev94.xray/283#site-footer as the others were repro

/LE: fyi https://gitlab.com/fdroid/fdroiddata/-/commit/361dbe524be4ec95ed333c5f20386e9e219191d6

**Comment by SaeedDev94** [comment]
Emm that's really strange !!  
I have no idea why  
Maybe it's a gomobile issue  
Will use a different version of go in my next builds

**Comment by SaeedDev94** [comment]
Fixed in new version: `v6.6.0`  
https://gitlab.com/SaeedDev94/fdroiddata/-/jobs/6728817518
