### ISSUE TITLE
App freeze if open logs

### ISSUE THREAD

**Issue by gersoctruda** [SaeedDev94/Xray#27]
It is difficult to debug the configuration if it is impossible to view the program operation log.
If I open logs program freeze. The program can only be resumed after stopping.
I use last release v7.0.0.

**Comment by gersoctruda** [comment]
Thank you for your work! This is a unique program of its kind!

**Comment by SaeedDev94** [comment]
It should be ok, the logs appears in real time but for low memory devices it can causes the crash  
I can show the latest logs but the user needs to refresh (to see the new logs, like v2rayNG)

**Comment by gersoctruda** [comment]
Thanks for your feedback!

My Samsung S21 plus have a 8 Gb ram.

I added a description of the log files to the configuration to solve the situation:
  "log": {
   "loglevel": "info",
     "access": "./storage/emulated/0/Download/xray-core/xray-core-access.log",
     "error": "./storage/emulated/0/Download/xray-core/xray-core.log",
   "dnsLog": true
  },

It is works for me.

**Comment by SaeedDev94** [comment]
Can you send the crash logs ?

**Comment by gersoctruda** [comment]
Where I get crash logs this app?
In xray log files no information about crash app.
I recorded a video that shows the problem.

Uploading Screen_Recording_20240703_165838_Xray (video-converter.com).mp4…

**Comment by SaeedDev94** [comment]
I mean logcat logs, you can capture it with adb

**Comment by maskedeken** [comment]
@gersoctruda I tried to fix the issue, try my [release](https://github.com/maskedeken/Xray/releases) and feel free to feed back

**Comment by gersoctruda** [comment]
> @gersoctruda I tried to fix the issue, try my [release](https://github.com/maskedeken/Xray/releases) and feel free to Thanks you!
Logs works it last release!

**Comment by gersoctruda** [comment]
Problem solved.

**Comment by SaeedDev94** [comment]
@gersoctruda 
https://github.com/SaeedDev94/Xray/releases/tag/v7.6.3
