### ISSUE TITLE
[FR] add config via url

### ISSUE THREAD

**Issue by legiz-ru** [SaeedDev94/Xray#29]
please add feature upload config to app via url

**Comment by SaeedDev94** [comment]
I'll work on this in future

**Comment by SaeedDev94** [comment]
https://github.com/SaeedDev94/Xray/releases/tag/v7.5.0

**Comment by gersoctruda** [comment]
I add url from Marzban panel. https://github.com/Gozargah/Marzban
Import works fine.
This App create simple configuration from url.

**Comment by gersoctruda** [comment]
I imported a link like this:
vless://***-***-**-**-dd18ef2f60ac@ip.**.***.***:443?security=reality&type=tcp&headerType=&flow=xtls-rprx-vision&path=&host=&sni=www.skype.com&fp=chrome&pbk=****************TqLNQ--****************RYlc&sid=#%F0%9F%9A%80%20Marz%20%28MDZ-22-AB%29%20%5BVLESS%20-%20tcp%5D

**Comment by SaeedDev94** [comment]
> oh wow, really, its work but there was a misunderstanding I meant support full xray config from url with rules =)
> 
> @SaeedDev94 pls check your email, to view my limk with full xray config with rules

Your link is dead

**Comment by SaeedDev94** [comment]
> and pls create url for this app for import url [like another apps](https://github.com/mercurykd/vpnbot/blob/a82147eeda726b28816f4c8675224e6026cb7042/app/bot.php#L4587): sing-box://import-remote-profile/?url= streisand://import/ v2rayng://install-config?url= hiddify://install-config/?url=

You mean deep link, right?  Maybe I'll add it in future

**Comment by SaeedDev94** [comment]
@legiz-ru 
https://github.com/SaeedDev94/Xray/releases/tag/v7.6.0
