### ISSUE TITLE
[FR] add custom geoip/geosite assets via url from Github

### ISSUE THREAD

**Issue by legiz-ru** [SaeedDev94/Xray#39]
For example from [re:filter](https://github.com/1andrevich/Re-filter-lists). It's very actual list for Russia.

https://github.com/1andrevich/Re-filter-lists/releases/latest/download/geoip.dat

https://github.com/1andrevich/Re-filter-lists/releases/latest/download/geosite.dat

**Comment by SaeedDev94** [comment]
My app already has this option, I'm sure you didn't open settings ever 😁

**Comment by legiz-ru** [comment]
> В моем приложении уже есть эта опция, я уверен, что вы никогда не 😁 открывали настройки

oh sh 
Really...
