### ISSUE TITLE
how we can monitor used traffic

### ISSUE THREAD

**Issue by itsDantes** [SaeedDev94/Xray#4]
thanks for your great work.

how we can monitor used traffic? i already opened an issues about it [HERE](https://github.com/XTLS/Xray-core/issues/2723).

please add more feature like **xray api statsquery** to this project so we can learn and use it.

**Comment by SaeedDev94** [comment]
Hi, Thanks for your interest to my app, currently I have no plan to add extra features, maybe I reconsidering in future.

**Comment by itsDantes** [comment]
@SaeedDev94 are you still have no plan for it?

**Comment by SaeedDev94** [comment]
> @SaeedDev94 are you still have no plan for it?

No, at least for now
