### ISSUE TITLE
vpn

### ISSUE THREAD

**Issue by jiangabc12138** [SaeedDev94/Xray#5]
time="2023-11-24T09:04:58Z" level=warning msg="[UDP] dial 8.8.8.8:53: client handshake: UDP ASSOCIATE: command not supported"
time="2023-11-24T09:06:33Z" level=warning msg="[UDP] dial 1.1.1.1:53: client handshake: UDP ASSOCIATE: command not supported"

Excuse me, how did you solve the issue of my error report? How did you link UDP to the proxy server or how should the server configuration file be configured? Is there a problem with the server connection? Because I use Android Studio's simulated mobile proxy to use it normally, I cannot connect to the VPN proxy server in real phones

**Comment by SaeedDev94** [comment]
Only arm32 + arm64 are supported
You probably can't run it on android emulator for now ...

**Comment by jiangabc12138** [comment]
![android](https://github.com/SaeedDev94/Xray/assets/151912938/dc9d2e6d-7443-4ede-a07e-2c2c89a22b65)
![config](https://github.com/SaeedDev94/Xray/assets/151912938/7bd98783-5cbc-4dcb-aa95-4cbc1e5e98c2)
![phone](https://github.com/SaeedDev94/Xray/assets/151912938/8ba7ecbc-3155-47fb-96d8-ec55e2b587b8)

My Android emulator can run normally, and the request link for APK packaging to the mobile end is also normal, but VPN still cannot proxy. How should I handle it

**Comment by SaeedDev94** [comment]
These are `tun2socks` logs BTW  
There is a high chance that your system doesn't support arm, you can download the right version of `Xray-core` and put it in `jniLibs` directory if you are persist to run it on android emulator
Also make sure your config is valid

**Comment by jiangabc12138** [comment]
Can you take a look at your server's xray configuration file

**Comment by jiangabc12138** [comment]
Can you take a look at the xray configuration file of your server

**Comment by jiangabc12138** [comment]
Can I have a look at the xray configuration file of your server?

**Comment by SaeedDev94** [comment]
> Can I have a look at the xray configuration file of your server?

Sure, I'm using this template:  
[VLESS+TCP+REALITY](https://github.com/SaeedDev94/xray-example/tree/master/VLESS%2BTCP%2BREALITY)

**Comment by jiangabc12138** [comment]
Sorry, I don’t understand Android code very well. In addition to the socks protocol, can your Android code also use other protocols to directly connect to the xray server, such as VMess?

**Comment by SaeedDev94** [comment]
> Sorry, I don’t understand Android code very well. In addition to the socks protocol, can your Android code also use other protocols to directly connect to the xray server, such as VMess?

Dude, this app can run any valid `Xray-core` config including vmess  
Please run it on a android phone instead of emulator  
Maybe I'll add emulator support in future
