### ISSUE TITLE
Dear author, your code is excellent. I need an APK for the VMESS protocol. Can you use your spare time to write one

### ISSUE THREAD

**Issue by wanliyunyan** [SaeedDev94/Xray#6]

**Comment by SaeedDev94** [comment]
You can use any valid `Xray-core` config, please check this repo: https://github.com/XTLS/Xray-examples

**Comment by SaeedDev94** [comment]
It seems you have a similar issue #5

**Comment by wanliyunyan** [comment]
I'm using a mobile phone, not an emulator

**Comment by wanliyunyan** [comment]
I can successfully connect to my proxy server using InvisibleManXRay-x64, so it can be proved that there is no problem with my configuration, so how should I use your project?

**Comment by SaeedDev94** [comment]
I noticed that your config missed important part:
```js
{
  "inbounds": [
      {
        "listen": "127.0.0.1",
        "port": 10808,
        "protocol": "socks",
        "settings": {
          "udp": true
        }
      }
  ],
}
```
Also listen address + port must be same as your settings

**Comment by wanliyunyan** [comment]
I just realized that I didn't read the config.json configuration file. Should it be placed in the files folder under com.xtls.xray?
![ed4af5ea493a7a1b5f7843f52e96afd](https://github.com/SaeedDev94/Xray/assets/10751248/80881f33-c12f-4f0e-853c-ffa2baac94a2)

**Comment by SaeedDev94** [comment]
Emmm, I thought it's my repo  
You are working on your own project
So I have no idea what are you trying to do
