### ISSUE TITLE
 Regarding xray configuration file issues

### ISSUE THREAD

**Issue by Anselaaa** [SaeedDev94/Xray#7]
{
  "log": {
    "loglevel": "warning"
  },
  "inbounds": [
    {
      "listen": "127.0.0.1",
      "port": 10808,
      "protocol": "socks",
      "settings": {
        "udp": true
      },
      "sniffing": {
        "destOverride": ["http", "tls"],
        "enabled": true
      },
      "tag": "socks"
    },
    {
      "listen": "127.0.0.1",
      "port": 10809,
      "protocol": "http",
      "settings": {
        "udp": true
      },
      "tag": "http"
    }
  ],
  "outbounds": [
    {
      "protocol": "vless",
      "settings": {
        "vnext": [
          {
            "address": "",
            "port": 443,
            "users": [
              {
                "id": "59d634c2-4015-43c4-bb00-bcd9622fd202",
                "encryption": "none"
              }
            ]
          }
        ]
      },
      "streamSettings": {
        "network": "ws",
        "security": "tls",
        "tlsSettings": {
          "allowInsecure": false,
          "serverName": ""
        },
        "wsSettings": {
          "path": "/59d634c2-4015-43c4-bb00-bcd9622fd202",
          "headers": {
            "Host": ""
          }
        }
      }
    }
  ]
}

Hi bro, this is my client configuration. This doesn't work. What's wrong?

**Comment by wanliyunyan** [comment]
![fa3e8ab507d43593458c608acce911d](https://github.com/SaeedDev94/Xray/assets/10751248/c005771f-65ba-45f9-b260-e85288106b18)

The Great SaeedDev94，This is my configuration, I can't connect to the network no matter what，I can make sure that my proxy server is available, please help me，I can connect to the proxy server using other tools

**Comment by wanliyunyan** [comment]
@SaeedDev94 You can connect to my proxy server now, please help me

**Comment by wanliyunyan** [comment]
@SaeedDev94 I use Chrome to surf the Internet. It will prompt dns probe started at first, and then it will prompt dns probe finished no internet.

**Comment by SaeedDev94** [comment]
> @SaeedDev94 I use Chrome to surf the Internet. It will prompt dns probe started at first, and then it will prompt dns probe finished no internet.

If DNS is your problem then try to add routing config:
(Also add `"tag": "proxy"` to your outbound)
```js
"routing": {
    "domainStrategy": "IPIfNonMatch",
    "rules": [
      {
        "type": "field",
        "ip": [
          "1.1.1.1",
          "1.0.0.1"
        ],
        "port": "53",
        "outboundTag": "proxy"
      }
    ]
  }
```

**Comment by wanliyunyan** [comment]
thank you，I finally connected to my proxy server, but it was not caused by routing.

**Comment by wanliyunyan** [comment]
@SaeedDev94 I am Chinese. Without a VPN, I cannot access websites such as youtube. Now with your VPN, I can access these blocked websites and the access speed is very fast. But when I use Chinese apps, the access speed is extremely slow. Have you ever encountered such a situation?
